name: Lint

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install linter
      run: python -m pip install flake8
    - name: Run linter
      run: python -m flake8 --max-line-length 120 --show-source
  docs_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update docs
      run: python walbot.py docs
    - name: Compare docs
      run: git diff --exit-code docs/Commands.md
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Install pylint
      run: python -m pip install pylint
    - name: pylint version
      run: pylint --version
    - name: Run pylint
      run: pylint src/ tools/ walbot.py --max-line-length=120 --exit-zero --disable=W1201,W1203
